# Generated by Django 4.2.7 on 2023-11-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='image',
            field=models.ImageField(upload_to='insect/images/'),
        ),
    ]
