# Generated by Django 4.2.7 on 2023-11-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insect', '0002_alter_guest_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150)),
                ('image', models.ImageField(upload_to=None)),
                ('description', models.TextField(max_length=300)),
                ('treatment', models.TextField(max_length=300)),
            ],
        ),
    ]
