# Generated by Django 4.2.7 on 2023-11-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insect', '0004_alter_bug_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
