# Generated by Django 4.2.7 on 2023-11-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insect', '0006_medic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='medic',
        ),
    ]
