# Generated by Django 4.2.7 on 2023-11-25 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insect', '0007_delete_medic'),
    ]

    operations = [
        migrations.CreateModel(
            name='medic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=None)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('bite_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insect.bug')),
            ],
        ),
    ]
