# Generated by Django 4.2.7 on 2023-11-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insect', '0008_medic'),
    ]

    operations = [
        migrations.AddField(
            model_name='medic',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
